### ISSUE TITLE
Staff page CSS is broken

### ISSUE THREAD

**Issue by BrennanColberg** [frc3268/frc3268.github.io#5]
<img width="549" alt="screen shot 2018-10-21 at 00 46 42" src="https://user-images.githubusercontent.com/14948341/47264372-ca75cc00-d4ca-11e8-83e6-abadc6ca2a9f.png">
some import links are broken, and the CSS for the page doesn't load

**Comment by Volcore001** [comment]
what IDE are you using?

**Comment by Volcore001** [comment]
Fixed, I incorrectly copied the header info.
